### ISSUE TITLE
Update the library to support generics

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/roundrobin#8]
## Description
- [x] Bump golang version in `go.mod` to 1.18 and in relevant GitHub actions
- [x] Execute `go mod tidy` to format the go modules files correctly
- [ ] The library actually accepts only string items. It should be modified to support generics and use arbitrary item types. For example:

```go
func New(items ...any) (*RoundRobin, error) {
	return NewWithOptions(DefaultOptions, items...)
}
```

**Comment by tarunKoyalwar** [comment]
There are 2 possible methods to implement Generics here

1. Not strict (only using `any` )
- If implemented this way `roundrobin.New(proxies...)` will not work because
it is not possible to convert []string to []any so we have to do more changes
and type handling and is less strict


2. Strictly Generic (Using Constraints)
- This implementation is strictly generic so to invoke this we need to use
something similar to `roundrobin.New[string]("a", "b", "c", "d")`.

Either way it will break all its dependents i.e proxify and shuffledns .

This has more cons than pros so it was decided to skip this for now
